# Generated by Django 4.2.13 on 2024-05-18 19:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_right',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Answer Text'), size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=0, verbose_name='Difficulty'),
        ),
    ]
