# Generated by Django 4.2.13 on 2024-05-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0002_alter_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_right',
        ),
    ]
