# Generated by Django 4.2.13 on 2024-05-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0002_alter_answer_options_remove_answer_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
    ]
