# Generated by Django 4.2.13 on 2024-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0003_remove_answer_is_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
