# Generated by Django 4.2.13 on 2024-05-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0004_alter_answer_is_right_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
