# Generated by Django 4.2.13 on 2024-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0004_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typeOfQ',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (1, 'True or False'), (2, 'Text Input')], default=0, verbose_name='Type of Question'),
        ),
    ]
