# Generated by Django 4.2.13 on 2024-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0005_question_typeofq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typeOfQ',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (1, 'True or False')], default=0, verbose_name='Type of Question'),
        ),
    ]
