# Generated by Django 4.2.13 on 2024-06-07 21:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0007_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('UserScores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
                ('QuizType', models.CharField(max_length=255, null=True)),
                ('QuizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiztest.quizzes')),
            ],
        ),
    ]
