# Generated by Django 4.2.13 on 2024-06-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiztest", "0008_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboard",
            options={"ordering": ["score"], "verbose_name": "Leaderboard"},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["id"],
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
    ]
