# Generated by Django 4.2.13 on 2024-06-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiztest", "0009_alter_leaderboard_options_alter_session_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="QuizStatus",
            field=models.CharField(default="OPEN", max_length=255, null=True),
        ),
    ]
