# Generated by Django 4.2.13 on 2024-06-09 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0010_session_quizstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
