# Generated by Django 4.2.13 on 2024-05-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_questiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
