# Generated by Django 4.2.13 on 2024-05-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quizes.questiontype'),
        ),
    ]
