# Generated by Django 5.0.4 on 2024-05-03 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
