# Generated by Django 4.2.13 on 2024-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
