# Generated by Django 5.0.4 on 2024-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_users_joined_date_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
